### ISSUE TITLE
Importing fails if they're spaces in the path

### ISSUE THREAD

**Issue by dustinWeaver** [contentful/contentful-importer.rb#31]
If using the importer script from a directory with spaces, the script fails with the following error:

```
/Users/testuser/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
	from /Users/testuser/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `new'
	from /Users/testuser/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from /Users/testuser/.rvm/gems/ruby-2.3.0/gems/contentful-importer-0.2.2/lib/contentful/importer/json_schema_validator.rb:28:in `block in validate_entry'
	from /Users/testuser/.rvm/gems/ruby-2.3.0/gems/contentful-importer-0.2.2/lib/contentful/importer/json_schema_validator.rb:27:in `glob'
	from /Users/testuser/.rvm/gems/ruby-2.3.0/gems/contentful-importer-0.2.2/lib/contentful/importer/json_schema_validator.rb:27:in `validate_entry'
	from /Users/testuser/.rvm/gems/ruby-2.3.0/gems/contentful-importer-0.2.2/lib/contentful/importer/json_schema_validator.rb:23:in `validate_schema'
	from /Users/testuser/.rvm/gems/ruby-2.3.0/gems/contentful-importer-0.2.2/lib/contentful/importer/json_schema_validator.rb:16:in `block in validate_schemas'
	from /Users/testuser/.rvm/gems/ruby-2.3.0/gems/contentful-importer-0.2.2/lib/contentful/importer/json_schema_validator.rb:15:in `glob'
	from /Users/testuser/.rvm/gems/ruby-2.3.0/gems/contentful-importer-0.2.2/lib/contentful/importer/json_schema_validator.rb:15:in `validate_schemas'
	from /Users/testuser/.rvm/gems/ruby-2.3.0/gems/contentful-importer-0.2.2/lib/contentful/importer/command.rb:84:in `run'
	from /Users/testuser/.rvm/gems/ruby-2.3.0/gems/contentful-importer-0.2.2/lib/contentful/importer/test_credentials.rb:12:in `run'
	from /Users/testuser/.rvm/gems/ruby-2.3.0/gems/claide-0.8.2/lib/claide/command.rb:312:in `run'
	from /Users/testuser/.rvm/gems/ruby-2.3.0/gems/contentful-importer-0.2.2/bin/contentful-importer:12:in `<top (required)>'
	from /Users/testuser/.rvm/gems/ruby-2.3.0/bin/contentful-importer:23:in `load'
	from /Users/testuser/.rvm/gems/ruby-2.3.0/bin/contentful-importer:23:in `<main>'
	from /Users/testuser/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/testuser/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

This same issue would prevent the script from working on Windows machines.

**Comment by dlitvakb** [comment]
Hey @dustinWeaver,

This library is now considered deprecated after the release of https://github.com/contentful/contentful-database-importer.rb.

Sorry for the inconvenience
